version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dart_explore
    ports:
      - "5432:5432"
    volumes:
      - ./Postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
