name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Run tests
        run: mvn clean test

      - name: Build with Maven
        run: mvn package
